addons:
  apt:
    packages:
    - realpath
language: python
services: docker
env:
  global:
  - GITHUB_USER=joeblackwaslike
  - GITHUB_ORG=telephoneorg
  - DOCKER_ORG=telephoneorg
notifications:
  email:
    on_success: never
    on_failure: always
slack:
    rooms:
    - secure: "K39R+fEeiBddfKe6/NlsLvmngdB4TKVPec3xa/2Bf8pKxhJHBGR4g3X2f1Mpj3utiIf9zeNQmX0txBK0s0viSTOJhBz9RqXO/NAXIerclNBuowLHpSjCf19dCd2tbCgwelnvaWDqg7/rvMPIB42Pv2F0QNCIgynrsfKF2uh5wLj993Pj230IIp6faytqHkZukG7/2OUWI/UZmuxNw9+5BCmXJNsKQWyq9CwAm7rIDlZG8H7/9i967thC9jtdAEc3z1ii2kd2CZWt3cCEhPkKtT4KMCOyXcWEF3mPcvXoXQxMtzIPCnzHMEiLfwT66AYqLcbl/gVEL00cnIyFR1sZyOgWOPsY0FhKItfl5dERZs1zWGlIb3LjyeI7H9c98fow2HKmLuM3QCvNBb0bWYZfchhj0mO+AYOxApftH21rDyn77P1fm/9JG8N7tJyXUt1JjLp8uWQ4T1CxZSAqMeyqasyVwynQoz9Q0zFcT1HXfjrvakfMAlJ/bu+SDyiuP5GF+JtMtUVuX6hEKF1+LvZf1RreMcSt/6yaIhymf6k4b5jJCrAx25Z+2VWrInXQ0M4GYgewR36QqTERMfSNU2+hzYEvAa60OVTC5B0V39QlCdpn0d+YjAS/RfxDM5Mll0guqFxWq30IFIs+3mpO59DIzCO+jbcGe3nAAHnj5HtKlQI="

    on_success: always
    on_failure: alwaysbranches:
  only:
  - master

before_install:
- source scripts/ci/environment.sh
- make build-builder

install: make build

script: make test

deploy:
  provider: releases
  api_key:
    secure: "P4y039WTCACUI/l7l7v1ZiVthX/sZ1/UPDOvDv5cBX0cio9pF191x4IGlSARngNMVE58260i4MMVDlI+dVrf5V7AHkiEsqZEBHGfxoNPQI4aJl1AhfHwo+jJKILbtUqt2mfBLU4Xiav9aNNG8DcKj8/dBtCPYw4KNf7LYQuAFRmEzlIxqa4G4BxQEqOVOye8+3vB3anWG9Ye4wBQY+mQZFKA81dMliTACZoGyD1CmUPAoF76Hl4LGyY6yrlRqd7nkGMo1UyHlhMglG9R68HiySoreovDoLiJkOvBpd6hwK/R4RK8/6pip3f99LRNNu50ieRwMSx/F9O5qh1DeyUMHLsMifhZWRsZFRIGU6byVd71dlyaeIDoMWkKL2TYNILd6FC3C9gQKY6NcpO+YOOBvHqf5CY5mYnRvTX7RLnXpRw/bVCFa3w5zGWdAH/IaK8DZHEvTy/hx9sB/jyUggnYW+ZKIl62FDlwZ1xWviWOL3I7U6G3y5RCmmJ+17lddfPJoVH4gN3+T3Ki57tYKu3ziWJG+uv4pqE181iQU95rGuDkbneUOFvOGaxX8Uvl21R9QvMPUA5Vm39ZceMQvXkHZmoUYU2TOF42lbmz5C15S147iGoB2nPhVZyX8kXHgMkemLKtMagGyl/4Gxk40wptGMTnZHGyX+Guh7+7YEnCKdM="

  file: overridehostname/bin/liboverridehostname.so.1
  skip_cleanup: false
  on:
    tags: true
