addons:
  apt:
    packages:
    - realpath
language: python
services: docker
env:
  global:
  - GITHUB_USER=joeblackwaslike
  - GITHUB_ORG=telephoneorg
  - DOCKER_ORG=telephoneorg
notifications:
  email:
    on_success: never
    on_failure: always
  slack:
    rooms:
    - secure: "h73hz80sQ4jDTZuoy+B1VbrvhNTvjEwgnTCA1HjET3YoR/+TxaBx1f98kdvxtYnNVrYZG7aZn5mtChPHQxM2Lb6MBaviNPTXKCmHyqxvM55htcUu4khygSjDJiX3mQ/0KgWEGsIVdrpatr2n6JFuYpuh5QzNKUsTB1fO8vtaQWI8Mpsc9B+WNb1XY3IOJHRA8gV4Je2umg9fLKL9JQKwGXIeZy56u9EQWIhX/xQ/mwIrrL9B5x8pqBuwHwJBTeI/dCReXsGMEX8UfZvAnbMMhWocuYQDIwKHIz8eqoP5T3RHOaGQNf61isCnMGYEZ2RYN26yDHBlRsd83+9BaxQAxgrylZj4cr/ALJ3u2zuhCz6fTGqu+y0HLk8f+Lp3jTw6vd2jEIsgpI2YazB3A/2kxm5NeLwH7u2ze0E04cdtQ1OitTvPtwz7N6lA6ReTokuUcNCbB3BAPiQ4rmgXE40JdlNnon/LKPOswWjIkJuetk0KUmgfNpxhQsYQA4vWVca8PVg5syWqq2V50A/dbkn999UboLKi8QhiAc4gcN8V1oRe+lYwbQSONrcnJJECyYvMCDBRrd7VH3ifDM3YBPTlcV4w6Dh7aMnslPe5O1fzLJkKeXNZG7MSO+iBWiLPher+n0mRYWAPx3PNYqiOBVXOZ6CdIUzZ3R8yb4aQxJrYsKw="
    on_success: always
    on_failure: always
branches:
  only:
  - master

before_install:
- source scripts/ci/environment.sh
- make build-builder

install: make build

script: make test

deploy:
  provider: releases
  api_key:
    secure: "l9ncnFQD7PVsJTWhjekyykPDLo+Y8iSxIcKBmo9FjBpsE541VmyjZox4XD/Y+aZyvFNgMxFKaPT+YeqcDGP+Moq2SvBB1FaU4Z8k6+CERsaTKpVHwTRBDs68klKCiX+KAdokwOkDMDBmIqEuaBt5OOCTgxH6Xoe3obezXUHjvfrUWFYQ1KRXBeXKiW+wL5kY5Jbm6ofsa7DekDKFgTdbBtm6S92jRBfi7QPbi8TnrVaGNh6mDMegRyHn99Ms11aFfr+tUsqCsy3bzoYXp2cRkXKPQnh9BakcPiedMpVpeqEs6B2vTBKfHPbVdSBColLPRALbfye+qOOW8884aTC6BtwJV1SuuEZYUG3p+IPHIgednamMJ44onGX+NoFfoZWyWp9MULfw3ZE0mvHomYecNkrDGCy4NayF7THu8KvIHslU8kSFDuwCoaz3bp6IPS6FijWISTS8pHBAk5l/+slzY8RWp4ZV4r9iQEYobcFe5hA9jRbxeQAPa4c26o0eITPxigt6mQ1VvCTQPgYb7acR69Pwmxn/j8xdXtWUdR7s6tY5Tw7XBW1k5V0HbZ2e0BxzTlOgQ4wIDwjXE0editsPua5MgVABe7d0GgtOVb5WCoQZg62qbj8zwXcyPRDCcYanwEkcuOiPQdxOoebHrsjClglUsN66ejPjFl8KddDRjlw="
  file: overridehostname/bin/liboverridehostname.so.1
  skip_cleanup: false
  on:
    tags: true
