addons:
  apt:
    packages:
    - realpath
language: python
services: docker
env:
  global:
  - GITHUB_USER=joeblackwaslike
  - GITHUB_ORG=telephoneorg
  - DOCKER_ORG=telephoneorg
notifications:
  email:
    on_success: never
    on_failure: always
slack:
    rooms:
    - secure: "T1ufLh6LCoPbgbeTT6OrB7I4QH5kVaa2xro9K1AKDDR129zJGF7TymQzVo2WZH0BwlLFBG3CCEGAag2GDbYe380dgVqw8LQrcF1zyVio/6E4t+ibm38hLzEiiswJp4WXzqfVR/svLNdBHF/TO9BSaF0SC5mfC9kzZTWitM1gMnL5MHMMg336NVT1dJjTAs60BfgypSOkp9ofQwFN5uniXDR9FLx1g3cxE0ZaufzclghV4K19Ftjb+ohOYE0zGnn/IZgMKF+Smc5kEEqlV66MMMJxbHiFm5/KIdFgziRzIhDihVaCaclCxglWigvoiENGL4U6F24jlZjWnAw0khQEVtkCo3yO//79tshCmSaGpcMD+CF6m6IMW+jKezDH40Mg8+WpNx9STSZcAAtFWizBYta/4YO3kqBTwLy7NPeLdeIE6GLsMgwgMrUk+x/1GRge4mOAJOncw+5jJcYZtxUM2yi6Jdz4g9s+L3qI3w5DW5JMlN6VI73yBWTg04O5yQ4skZEkc4Rmp3Vmj7cIIpA97nIUdj5maI0mJHcKMuNXzRa6Xe9Yd8K/a/cMPKAZ3KDpAnsBLRchlcJfAZ7y9FLowwxOrLVaZJhJpJ6upXpWZMZHvhC6WCQP4+VQGaPkP9JbM3zI1ZW6OWDRzU00gOejnbNiOB33wX6tZ7uYgNz8tyQ="
on_success: always
    on_failure: alwaysbranches:
  only:
  - master

before_install:
- source scripts/ci/environment.sh
- make build-builder

install: make build

script: make test

deploy:
  provider: releases
  api_key:
    secure: "Hz1DJknL+jRvrBrmdUD1nJ0CiICy5H411IRWYUTNeZUDc38nd+x/vIaO49w/4dpLl88TESEiWX+kFfYOxwEPCobDlJE6O+RnEyKL2yx3eYGana0w0rXL+Fl4CuD8m8gT8oga5ja1RoYisSH4sQUnZeM1Dn48TMTGcikCAJMsp6pJ+A3lUzjF5eDyiN8BonQxAW3izoM6gCLL4S49amrmJE5ejmQ7rW2YkpnZUSte478KHPCHpCgZclQquOBzXsJ6m9ZJfCYIa7joc/1XjIl4zAUW1wNLMfIroGB7/bPV0BSC9ovT6QJmch/E+/ZEQ1SBL5TRGUGVHumgaZ8zp7RPDPiPMqBjy2QHCd2fyBhAmwC6qAO+EqYULK9w7w32sHb7HqZCOsxGAPE5EhN2wiZYAFVAapIXWWAZcm0AVNp4wF65dPVR4pdXZdVF63Uwx2Q4dOv/B516Uq6/pMhj9DP/yNlrZ24QkkpV8r7LgJnAJS4wVX4teAs5mh0PNOTuZz6A410grW16Cp8bnHj0yyXpe1k24BZo92lYmElZLbjHSu9G1kd84Fhsm1I2bG7ejVrxQQkYUpVzJZdkYKUroZuE6+lN+M/LN+rZzrsdurZIWMrZXWYA45paRvHX/SR7/woRC0xZ0vq5cYd9kOWuLW4scqENCwvIH0nDPFwdHzHAyRE="
file: overridehostname/bin/liboverridehostname.so.1
  skip_cleanup: false
  on:
    tags: true
