addons:
  apt:
    packages:
    - realpath
language: python
services: docker
env:
  global:
  - GITHUB_USER=joeblackwaslike
  - GITHUB_ORG=telephoneorg
  - DOCKER_ORG=telephoneorg
notifications:
  email:
    on_success: never
    on_failure: always
  slack:
    rooms:
    - secure: "fxnFvLqWwq0RN7pyHwt6HVz+F6LypBq110LJ1wWPKVH7iUmASTHQ39mtunkqAF1/CuKnVgx7P3Pjf4NMFlfUs5zZEFsjU7m2A1Amfstncn2L7BXpH3OsWPQSEiV4hSmsVZdUQ5hLjd8ExRDObIljrZYFbszSEsxTBRSkv5KK1AkuDmrh5CapPY0A95xEwYhun4iSwG5tPG8jYmXI6P8RaKERSykobq9expiLF9pjl8upv9VDReas3D7TmjX8lbMMbt3R7sNPapjbe0qul34Uf3aIorv/wXSX0Kjn3HZpY7O6xttuROj1p4+Oz2vV/+APDslPeor1X0hGcfvSX+n/3R9tqB2ilhJY+NnHuTV6s5QPjcxh7/fut8zRBfccDFoRzukTgBHsFx1DdkamVjU2zjVXfKmQCxBGbLzuQnBHK2B8qbETj2fpOPac52nujgQ19buL0rfA6qIug7AHiswovyiRDanfs6cgNQFyOw6d7nx6DMu9oauM9N/84LrxhfEGReJ4RCWh4sHJNqDTmhwrjKcat7DigfjQh4xi8Bpq5aDVpP17eerWKNNj0AD4LL0Q/A2n62KXvMr2fV6hSvi/2h/Gw39F0QdeFssZXzmKobZO6E7UDac8Ht2MQuTLhHJCIi/6HnMXpEJSAcbcCqK8LtQcfCZV0W0z8OQ+iw6cLNY="
    on_success: always
    on_failure: always
branches:
  only:
  - master

before_install:
- source scripts/ci/environment.sh
- make build-builder

install: make build

script: make test

deploy:
  provider: releases
  api_key:
    secure: "jJdkx1VmgT8vFQ4yFRQuwH+34WFwjof6qt/aRM9SngPRWM2r2gR2FsYf+ltqWDScNv6TmzGUgrdffKjNFuBkokQMsK5/ILmEAU91iiWn0kptAJfA5ucPwFOjRNGdyowiA2ppIb2mXj2XvM5wZemPnfzu9RX42SVzUFKiQmYorFcWOCKwwbKQPIdWRsT2Q4joWuzqowBISiDtFe6GDJnk6y7rbZ+BLzNwSSb21uhveMTqMHNO23s7Sm9+PIKr77VWmNjztBTSH9GDrRi4+e1GVIh8Y2Pl5CGrqReo6EeBBUOVaVvXtc/qTqyLCPbQqx5RmdKBxO2zWMe33M2K2WI9uCgeJg7JMOf2EecOWTcQoCF7Ms1M8ypkW3+R21bvqFAVrmZFAOqFxTLLRhrvnFJo6XQSrm1/cw0LpELTFvzL/sojULsZ7Ml1At05qmxTNs6/0yUblgfnY29BfjhOw/1TYqtWlqbK/0hqFIou4TdO7V4xfs8URHVJohRldWz5vh8+PAgHIT2kQcs9v1W4PXl75p4/IJG7xk8Y5brPfgssk4sWRR9outlTv8prNvFKsQ3ysAdqKTd6Q3N+cKaCIQ8WY63iy52gHQXT6n1iPkXjk753eoMWu7/YIdf9ED1Wz/OXNBxZaYUBi0uL0LVP7mj4Seso8Dittp335Sv/ItYXbOo="
  file: overridehostname/bin/liboverridehostname.so.1
  skip_cleanup: false
  on:
    tags: true
