addons:
  apt:
    packages:
    - realpath
language: python
services: docker
env:
  global:
  - GITHUB_USER=joeblackwaslike
  - GITHUB_ORG=telephoneorg
  - DOCKER_ORG=telephoneorg
notifications:
  email:
    on_success: never
    on_failure: always
slack:
    rooms:
    - secure: "Yxx+wG6UdUBpHj5vs/4fCTlUU7eLFm93h0UQJwqpX6WqN0gVNCXt6ag9WGwcH/ROaKnzxQQK+479IoQ2gHaLiOw5CCWi9FqnLmGajIiqcjPgRvB0NjuocL2NJFXXuFaHFb4wuagNoz4wC6geXuY60d2edonnKJ8AlLgOXCVWa3sblpl6VtBk6QE+VmzSkYM08bhl4pAhc84K9FAMNw1XgB34/O7Ws8rvYVBF+O9KV3iEEgrkGOKgTu+4TRF8DCnWOa5IksM6kRAVG0cXylZ4DcVyCxnzm967uK6dUYQJwQt18DWsco6NhoqHLyv0DxabKhHWQJoqbZrKspXrjX/SIdd/PsHDX31ItXQCvLOdKsgH/amqbT2CyjB1exHlSRb2YM9r/xC84t76JBLxX8C6YwEMgq84QCOWsod0TUQoOLy6iK3ap8CGE53WnCt0VmP/D9JlkpToIx8/ac7GUrJUcG2E51my8/UKOlHCN/ZNHvsBPw8Yai6KT8bZxGnF9xNqKMeZYWUv+yrdA8Vz7UR9sycD3wdDpGK1X5ID8sQ2LVUjt1BMbAgbqeLn4+sRRWG2jn33QpgEav1KBw++OdzDTTbXSW5FifmS/xxFIu00Hj2jCiOVBbQywiVTZ/LIhA2ZYJAtat+AZYdcopEum5/9Rmb0kE+h/SU+kazZ/TLcmlo="
on_success: always
    on_failure: alwaysbranches:
  only:
  - master

before_install:
- source scripts/ci/environment.sh
- make build-builder

install: make build

script: make test

deploy:
  provider: releases
  api_key:
    secure: "CsBBES4EtKbMr7VLnzBC9f//YYdIaETnwj4SOq4ghjL2wYm4RQkkhjxE12MXA6+okUv2BTBA7uj1R0yvpZdj9JgnadPbxVUqaob5v7druGD0AEx36qEqgx7Ri3KtnErInqMrpL+ZkrfC4VV0kB8Wi8HbCMgwF1PS1mkNsvg6Or087cjnAMjwAIjLOiUt32AXEUyajP2UumOl5ltW0qqTDtxGq3OXrb5JblMz82CWnWQsogK2tfkWpPOkRLg2gSMsyhDdX9yeQAn79vhLIOVsXvuSDR8Iy4NWcfyetjM2sKFbmJdeOZWszhCtZEwu7yLevI7AZmdKH7v0SjL1odHfhoEVdVv/aqzRGX9ltECIVD+zegHJA/zMZeyQ7opA1vbFTDtRz79oJuPWHyuN06y724nQzlbwWDQhOeimcvUJMDOFZ76PqwS2nKeFJGxclKuKfSA0LrcUl0hdJjQd1ZHHWvimRpkspX0Rl1/M8RdLQ9ue+ZAF2tOhe7DWiTtfJnPUuwgsZ/tdJ1Juv2zg5NduewG/BAhkn/c90lcXhGG0zcL7p3pKtDSnONs8xfXIezYV6fBW8YfARbSFrPuoi5SshtIb9BsWufBitOotgzhZNwlmDj6uV2GP+uLF0zmxcfF8HEeG+aUiqG6E4x3Gam4UJev2zm0tYTZCh+6L9jpRxoQ="
file: overridehostname/bin/liboverridehostname.so.1
  skip_cleanup: false
  on:
    tags: true
