addons:
  apt:
    packages:
    - realpath
language: python
services: docker
env:
  global:
  - GITHUB_USER=joeblackwaslike
  - GITHUB_ORG=telephoneorg
  - DOCKER_ORG=telephoneorg

notifications:
  email:
    on_success: never
    on_failure: always
slack:
  rooms:
  - secure: DRXPKBZU3Xv5JjrvLnkPZL5q4++qlZ/rf0slr1hepNNwW3KJSzjjJw2D4fEnCprBUAd+6PC+EiIZifL+E+GBfOA2rQ3TiUdl6Ri2LGVKWw3WwFbW/3+TxbKqQ+Uh0lzvw+xqDOv7jGYAgvc6lbrp1ScLGynO2NMj2+VPlq2TVvqhDItrqCNsKIgJzEJcvMyvqHivubM/356ibXeoB5Q6xscfh4sxSsf1C5Zr+sLW3PFiNORKXC+Fi6PAtaNGtphjFN+K/NM2PuNTXov88ygOREJ2hS3bKzvJuoWptBAGNa5vAN8BQSIjR59QKI4ZvAdI4T+m2gzuDZVXhehZn2aztnDHprqpAGbVN7an+cqN1tVKCOPeXqu4x6G+ndnGXR9TbE5o08TQP/xGlCTPQgHPS8Jp3avXaBk0XDCByAGAZboZKjqIzkeQyv0FXB8XNgPWzXHzUYTTvR4IH67o071iaSijtgukKbI1Mft6BwHvKk25O5QqsRsSvBJlPXJhigbo0OaHd0BtWRcyG8uh80RR3pdhQPDe9qXE+ZIy1jawe2IyPy6ra+qYUVivMjQn8V9XL9BUO34BWe9mwrr+zSUyTq1iPmKqxg4cwEN/Cm+5aoHdo0EbaTsTCEfC+AH2/IhkV0Ix1IECA+uCWvwVME/PLzbD5DTLmyQqqOhZL92aPWI=
    on_success: always
    on_failure: always

before_install:
- source scripts/ci/environment.sh
- make build-builder

install: make build

script: make test

deploy:
  provider: releases
  api_key:
    secure: lbDISb0CHQTq00Alo7ex3W+X0p+K6zgsl8ui9vR0ueD8UMwXpGbjIWLPBo+8U8EKv5p2j4Zg6Ct1fRfE42uf/xVWLDq8ILD4TDrKw/839l0MF8dgyWfLpgF2gkAX4ZsZho0xUrVB9uKO+p/pVIck7SgRn8BR1UWqZ4nRuCzkOvHNeThXf9Qpz4NAIwWa5MtWWT8Aq0CyhtY79CJMqn8UyDkGms37C7Fc2nh3htuOtBEC8UeeaBes6HFgaK5mhgHLPEfz523ll1k/xkXE4/8CzF52oeLntbG/LHL95XBmldghvASV6Ct9kNYLr6F/gWPF/KCVshCd5dxMYL27IaG/hN6BrqwuTg5MeDEh+RPODzInjmYk3BW9jBob8jtivwedUkoMtZn6AFVEWhmCvYETv1Sh3g/VzFcQwh9Kcs0Z7u2JRbKMhAoUToKEbjpo1hS3o2O1QPigeTKokgrBwm9V6xuaQnlx4hDACAPu4sA6WBujXeiVAGeAgR4PN3++T5qJK39TehsITODQpXSWwEoHJ56bpI/h+/LAmEOHa2FerjznTmUlghqhaDf8ky6vJ6G6xDBnMjTgLkfkU8bgg+m+o/S1xveLA1zbshwtr08UysXPDY55fxl1KRotmvkbNcaZCC0cB0Nfo6eN6yqhAbvRtRFpTEr4tAacP7EcoG2AvRw=
  file: overridehostname/bin/liboverridehostname.so.1
  skip_cleanup: true
  on:
    repo: telephoneorg/overridehostname
