addons:
  apt:
    packages:
    - realpath
language: python
services: docker
env:
  global:
  - GITHUB_USER=joeblackwaslike
  - GITHUB_ORG=telephoneorg
  - DOCKER_ORG=telephoneorg
notifications:
  email:
    on_success: never
    on_failure: always
slack:
  rooms:
  - secure: "DRXPKBZU3Xv5JjrvLnkPZL5q4++qlZ/rf0slr1hepNNwW3KJSzjjJw2D4fEnCprBUAd+6PC+EiIZifL+E+GBfOA2rQ3TiUdl6Ri2LGVKWw3WwFbW/3+TxbKqQ+Uh0lzvw+xqDOv7jGYAgvc6lbrp1ScLGynO2NMj2+VPlq2TVvqhDItrqCNsKIgJzEJcvMyvqHivubM/356ibXeoB5Q6xscfh4sxSsf1C5Zr+sLW3PFiNORKXC+Fi6PAtaNGtphjFN+K/NM2PuNTXov88ygOREJ2hS3bKzvJuoWptBAGNa5vAN8BQSIjR59QKI4ZvAdI4T+m2gzuDZVXhehZn2aztnDHprqpAGbVN7an+cqN1tVKCOPeXqu4x6G+ndnGXR9TbE5o08TQP/xGlCTPQgHPS8Jp3avXaBk0XDCByAGAZboZKjqIzkeQyv0FXB8XNgPWzXHzUYTTvR4IH67o071iaSijtgukKbI1Mft6BwHvKk25O5QqsRsSvBJlPXJhigbo0OaHd0BtWRcyG8uh80RR3pdhQPDe9qXE+ZIy1jawe2IyPy6ra+qYUVivMjQn8V9XL9BUO34BWe9mwrr+zSUyTq1iPmKqxg4cwEN/Cm+5aoHdo0EbaTsTCEfC+AH2/IhkV0Ix1IECA+uCWvwVME/PLzbD5DTLmyQqqOhZL92aPWI="
    on_success: always
    on_failure: always

before_install:
- source scripts/ci/environment.sh
- make build-builder

install: make build

script: make test

deploy:
  provider: releases
  api_key:
    secure: "W/t1303ja2TPgTZJLjAdbpKCap9DoidIGlf6KM/lOECHp8BnFagkegbT5vtTqavpQuFhOKdLKZ8dONwJ1ggJIoHbWt5Gw6hNsqnMaCcnAtrZ9RYRxwGq+znPvJRJFMOw3yPCeNRmpSfzYY7jnd06Z30ylrtohA/Yga3veOX5fZz/2Ayq2YdZgAfSa0k+h2yb6NuZbcle3mUhHnj0x/Cp0jFfEYQC0xV/fMkzcQ1xiz8WNTUFb/zYpjbcMXg3QS2EvS4inIkBoo9IiBWiDIeW03Y42IUHEzGF7ax9uQYgIGb6IRMTf3Kjh0p4vZXiyz2N/3hHTtg9y6lvkHZWu3JucBWQxh92VQr6MLLGJ25pZS4ctfJ+3v6MkbHzskMXreigmiWsU7Q2h4QxPX/zqis7DdSZfUw8W4rgCJsD1+AZ/7Xeu/zWQY1Zr29RtLv2DBQiKMJrBc78FxALtitaahSjxVsPflFZ1OkdlddXNHYX7VoTtYrTF3lF9B3lVSYjOYJXuMGh9nHHne7KcXxpo/WfLVzIH7lcN+ca3T6qywprMZTy6DtLnHD3SvFRbRJuFrjvrAVhe+3NAUImJp4L1tcIoBUNV0/OM8afLGP5gqw4z5Vnmf9MbaBWaw2Oz6JLa6AM1o2tfJU4+YZg/mOu7FI5fBBG3aCClg9ZBDUPbp60H6E="
  file: overridehostname/bin/liboverridehostname.so.1
  skip_cleanup: false
  on:
    tags: true
